name: weather_underground_api
version: 0.1.0
author: Ira Burton <ira.burton@gmail.com>
description: A Dart interface to the WeatherUnderground API
homepage: http://goo.gl/ZoMN5

#dependencies:
#  unittest: any